# Catppuccin-Mocha
include current-theme.conf

#font_family JetBrains Mono
font_family FiraCode 
bold_font        false
italic_font      false
bold_italic_font false 

font_size 11

background_opacity 0.9

cursor_shape block
enable_ligatures true
